### ISSUE TITLE
archub pkgbuild revision

### ISSUE THREAD

**Issue by FabioLolix** [nbebaw/Archub#1]
Hello nbebaw, I have seen your archub pkgbuild from the new pkgbuilds feed and revisioned it

*  archub is a disguised `-bin` pkgbuild
* pkgname don't have to be used in `pkgdesc=`
* `arch=` can't be `any` for bin packages which are cpu specific
* git makedepends is not used or needed
* git checkdepends is not used or needed
* depends don't have to be in the other *depends section
* downloaded file is unversioned, this inconvenience users
* skipping *sums is a bad packaging practice, please use sha256 or higher
* the license should be installed in `"${pkgdir}/usr/share/licenses/${pkgname}"` since it isn't a common one, see Arch's licenses package

Here's the revisions:

* stable from source https://github.com/FabioLolix/AURFIX/blob/main/a/archub/PKGBUILD
* VCS https://github.com/FabioLolix/AURFIX/blob/main/a/archub-git/PKGBUILD
* bin https://github.com/FabioLolix/AURFIX/blob/main/a/archub-bin/PKGBUILD

***

Also your boostchanger-py and boostchanger-git pkgbuilds have several issues like:

* boostchanger-git isn't a VCS pkgbuild
* using pip install
* using $pkgrel in source=()
* installing stuff under /home/ is prohibited
* removing source 
* download with wget in package
* unzipping some the archives is already done by default

**Comment by nbebaw** [comment]
Hello Fabio, 
the issue has been fixed in the new version. Thanks

**Comment by FabioLolix** [comment]
Several things are  not corrected,

* archub is a disguised -bin pkgbuild, it need to build from source since the program is open source; if you want to repackage the bin please reupload as archub-bin
* the downloaded archive is unversioned
* if you download cpu specific files please use source_x86_64=()
